[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.gorbchain]
profiles = "GrJrqEtxztquco6Zwg9WfrArYwy5BZwzJ4ce4TfcJLuJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.gorbchain.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"